# Generated by Django 2.2.12 on 2024-11-29 04:55

from django.db import migrations, models
import kuser.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othernaturalperson',
            name='id_number',
            field=models.CharField(max_length=50, validators=[kuser.validators.validate_id_number], verbose_name='Id number'),
        ),
        migrations.AlterField(
            model_name='othernaturalperson',
            name='phone',
            field=models.CharField(default=1, max_length=15, validators=[kuser.validators.validate_phone_number], verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='id_number',
            field=models.CharField(max_length=50, validators=[kuser.validators.validate_id_number], verbose_name='Id number'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.CharField(default=1, max_length=15, validators=[kuser.validators.validate_phone_number], verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_number',
            field=models.CharField(max_length=50, validators=[kuser.validators.validate_id_number], verbose_name='Id number'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(default=1, max_length=15, validators=[kuser.validators.validate_phone_number], verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
