# Generated by Django 2.2.12 on 2024-12-06 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kuser', '0002_auto_20241129_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='validity_period',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Validity period'),
        ),
    ]
