# Generated by Django 2.2.12 on 2024-11-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='library',
            field=models.CharField(blank=True, choices=[('Scientific and Technical Library', 'Научно-техническая библиотека'), ('Technical Library of the Minsk Branch', 'Техническая библиотека Минского отделения'), ('Technical Library of the Baranovichi branch', 'Техническая библиотека Барановичского отделения'), ('Technical Library of the Brest branch', 'Техническая библиотека Брестского отделения'), ('Technical Library of the Gomel branch', 'Техническая библиотека Гомельского отделения'), ('Technical Library of the Mogilev branch', 'Техническая библиотека Могилевского отделения'), ('Technical Library of the Vitebsk Branch', 'Техническая библиотека Витебского отделения'), ('Orsha Library Point', 'Библиотечный пункт Орша'), ('Library point Molodechno', 'Библиотечный пункт Молодечно'), ('Luninets Library Point', 'Библиотечный пункт Лунинец'), ('Library point Volkovysk', 'Библиотечный пункт Волковыск'), ('Library point of the Brest Locomotive Depot', 'Библиотечный пункт Локомотивного депо Брест'), ('Zhlobin Library Point', 'Библиотечный пункт Жлобин'), ('Kalinkovichi Library Point', 'Библиотечный пункт Калинковичи'), ('Osipovichi Library Point', 'Библиотечный пункт Осиповичи'), ('Polotsk Library Center', 'Библиотечный пункт Полоцк')], max_length=255, null=True, verbose_name='Library'),
        ),
    ]
