# Generated by Django 2.2.12 on 2024-12-03 14:03

from django.db import migrations, models
import klib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0003_remove_company_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseedition',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[klib.validators.validate_year], verbose_name='Year'),
        ),
    ]
