# Generated by Django 2.2.12 on 2024-12-03 14:17

from django.db import migrations, models
import klib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0004_auto_20241203_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_code',
            field=models.CharField(default=1, max_length=9, validators=[klib.validators.validate_bank_code], verbose_name='Bank code'),
            preserve_default=False,
        ),
    ]
