# Generated by Django 2.2.12 on 2024-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0005_company_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='edition_subtype',
            field=models.CharField(choices=[('MAGAZINES', 'Magazines type name'), ('NEWSPAPERS', 'Newspapers type name'), ('BOOK', 'Book type name'), ('BROCHURE', 'Brochure type name'), ('STD', 'STD type name'), ('INFORMATION_FLYER', 'Information Flyer type name'), ('STD_CHANGES', 'STD changes type name'), ('E_RESOURCE', 'E-resource type name')], default='BOOK', max_length=16, verbose_name='Edition type'),
            preserve_default=False,
        ),
    ]
