# Generated by Django 2.2.12 on 2024-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0006_baseorder_edition_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='edition_subtype',
            field=models.CharField(max_length=16, verbose_name='Edition type'),
        ),
    ]
