# Generated by Django 2.2.12 on 2024-12-12 12:38

from django.db import migrations, models
import klib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0007_auto_20241209_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='year',
            field=models.CharField(default=2024, max_length=4, validators=[klib.validators.validate_year], verbose_name='Year'),
            preserve_default=False,
        ),
    ]
