# Generated by Django 2.2.12 on 2024-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klib', '0013_basearrival_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='edition_subtype',
            field=models.CharField(choices=[('MAGAZINES', 'Magazines type name'), ('NEWSPAPERS', 'Newspapers type name')], max_length=16, verbose_name='Edition type'),
        ),
    ]
